name: deploy
run-name: ${{ github.actor }} is deploying frontend from branch {{ github.ref_name }}.
on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches: [main]
jobs:
  deploy-frontend-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm run install:frontend
      - run: npm run deploy:frontend
  deploy-frontend-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "::error Tests failed. Could not deploy frontend."
          exit 1